### ISSUE TITLE
Directives Tracking

### ISSUE THREAD

**Issue by wbhob** [CaliStyle/angular2-intercom#10]
I think we need to develop some directives to tie/hook into Intercom. If anyone has other ideas about what to put here, please add it as a comment below.

Current Plan:
- [x] *Show Intercom*: show a new message window
- [x] *Show Intercom with Message*: Show a new message window prepopulated with content
- [x] *Track event*: Track an event by name
- [x] *Log Out/Shutdown*: shut down intercom, for use on a log out button

**Comment by wbhob** [comment]
@scott-wyatt I'm going to make some changes shortly, I'll let you know. Can you put them in an beta channel on NPM (not the primary channel so we don't screw up people's deps *yet*)

**Comment by wbhob** [comment]
@scott-wyatt if you just want to add me to the NPM page, that should also work. I'm also @wbhob on NPM

**Comment by scott-wyatt** [comment]
@wbhob you are now an owner of ng-intercom on npm

**Comment by wbhob** [comment]
Yay I published alpha 1.
